# Generated by Django 3.2.3 on 2021-05-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaonnuriPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('recommend', models.IntegerField()),
                ('unrecommend', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GaonnuriComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.gaonnuripost')),
            ],
        ),
    ]
