# Generated by Django 3.2.3 on 2021-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaonnuripost',
            name='board',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
