# Generated by Django 3.2.3 on 2021-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_gaonnuripost_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GaonnuriComment',
        ),
        migrations.DeleteModel(
            name='GaonnuriPost',
        ),
    ]
