# Generated by Django 3.2.3 on 2021-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210523_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
