# Generated by Django 3.2.3 on 2021-06-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='importance',
            field=models.FloatField(default=1),
        ),
    ]
