# Generated by Django 3.2.3 on 2021-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_page_importance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='importance',
            new_name='default_importance',
        ),
        migrations.AddField(
            model_name='page',
            name='manual_importance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
